### ISSUE TITLE
XML parsing fails for ihsmarkit blog rss feed

### ISSUE THREAD

**Issue by neeraj9** [willemdj/erlsom#70]
Parsing fails for [ihsmarkit blog rss feed](https://ihsmarkit.com/BlogFeed.ashx?i=Technology).

```
** exception throw: {error,"Malformed: Illegal character in prolog"}
```

Steps to reproduce the issue is as follows:

```erlang
application:ensure_all_started(inets),
application:ensure_all_started(ssl),

Url = "https://ihsmarkit.com/BlogFeed.ashx?i=Technology",
Headers = [], ConnectTimeoutMsec = 2000, TimeoutMsec = 2000,
HttpOptions = [{timeout, TimeoutMsec}, {connect_timeout, ConnectTimeoutMsec}],
{ok, {{_, Code, _}, _Headers, Body}} = httpc:request(get, {Url, Headers}, HttpOptions, [{body_format, binary}]),

{ok, {XmlNode, _XmlAttribute, XmlValue}, _} = erlsom:simple_form(binary_to_list(Body)).
```

I am using the the following revision of erlsom in my project.
```
commit 1a9ea1a16ed2cf0466c11608367612d8b05ea6ae
Merge: df4526c b4ef336
Author: Willem de Jong <w.a.de.jong@gmail.com>
Date:   Wed Feb 28 13:36:29 2018 +0100
```

**Comment by willemdj** [comment]
Your XML has a byte order mark. When you do_binary_to list(Body) you create
a list that starts with the three characters of the byte order mark. That
is not what erlsom expects, because the byte order mark only makes sense on
an encoded binary.

The easiest solution is to skip the binary_to_list/1 step, it is not
necessary.

Good luck,
Willem

Op wo 30 jan. 2019 om 03:42 schreef Neeraj <notifications@github.com>:
